replicaCount: 1

image:
  repository: ghcr.io/cristalcorp/hello-nginx-1
  tag: af7d9838a4402125aad26f65c108df351253ea16
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: hello1-dev.local
