replicaCount: 1
image:
  repository: ghcr.io/cristalcorp/hello-nginx-1
  tag: dev-a5ce66e
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: hello1-dev.local
