replicaCount: 1

image:
  repository: ghcr.io/cristalcorp/hello-nginx-1
  tag: f211df0ccbe23c13f87f94dd7feff892351ee128
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: hello1-dev.local
