# app-myapp.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/cristalcorp/minikube
    targetRevision: HEAD
    path: charts/myapp
    helm:
      valueFiles:
        - apps/myapp/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
