replicaCount: 3
image:
  repository: ghcr.io/cristalcorp/hello-nginx-1
  tag: staging-ce88d29
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: hello1-staging.local
