replicaCount: 3

image:
  repository: ghcr.io/cristalcorp/hello-nginx-1
  tag: none
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: hello1-staging.local